<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>f2718572-14eb-4c66-b29b-7d3a59611451</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.AppContainers" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.Azure.Sql" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.4.6" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects" Version="13.4.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Update="Microsoft.NET.StringTools" Version="18.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StockApi\StockApi.csproj" />
    <ProjectReference Include="..\SMPortal\SMPortal.csproj" />
  </ItemGroup>

</Project>
